# ACB CH2 Azure CICD Pipeline Demo Default Configuration

# HTTPS Listener Configuration
https:
  secure:
    host: "0.0.0.0"
    port: "8081"
    # port: "8082"
  # keystore:
  #   alias: "demo"
  #   path: "keystore.jks"
  
#  truststore:
#    path: ""
#    insecure: "false"  
  reconnection:
    frequency: "3000"
    attempts: "3"